version: '3.8'
services:
  twsimulator:
    container_name: twsimulator-dev
    build:
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - rust-cargo-registry:/usr/local/cargo/registry
      - rust-cargo-git:/usr/local/cargo/git
      - rust-target:/app/target
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  rust-cargo-registry:
  rust-cargo-git:
  rust-target:
